---

- name: install nginx web-server
  yum: name=nginx state=latest
  tags: packages

- name: configure nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
        owner=root group=root
  notify:
    - restart nginx
  tags: deploy

- name: remove nginx SSL directory
  file: path=/etc/pki/nginx state=absent
  tags: deploy

- name: create nginx SSL directory
  file: path=/etc/pki/nginx state=directory owner=nginx group=nginx
  tags: deploy

- name: set nginx SSL certificate
  copy: src=questionnaire_ca.pem dest=/etc/pki/nginx/questionnaire_ca.pem
        owner=nginx group=nginx
  notify:
    - restart nginx
  tags: deploy

- name: set nginx SSL private key
  copy: src=questionnaire_ca.key dest=/etc/pki/nginx/questionnaire_ca.key
        owner=nginx group=nginx
  notify:
    - restart nginx
  tags: deploy

- name: set nginx SSL dhparam pem
  copy: src=questionnaire_dhparam.pem dest=/etc/pki/nginx/questionnaire_dhparam.pem
        owner=nginx group=nginx
  notify:
    - restart nginx
  tags: deploy
