---

- name: Install system packages
  become: yes
  become_method: sudo
  yum: name={{item}} state=installed
  with_items:
    - epel-release
    - git
    - make
    - gcc
    - tree         # Optional
    - python36-pip
    - python36-devel
    - python36-virtualenv
    - sqlite3
  tags: packages