---

django: True
django_migrate: True
django_collectstatic: True
django_commands: True

web_app_name: pyquestionnaire
web_app_path: /opt/{{ web_app_name }}
version: master
web_app_user: "{{ web_app_name }}"
git_repo: https://github.com/oguzey/questionnaire

bundle_dir: 'files'
env_dir: 'files'
env_file: "{{ env_dir }}/{{ web_app_name }}.env.{{ inventory }}"
